import 'antd/dist/reset.css';
import type { Metadata } from 'next';
import { AuthLoader } from '../lib/redux/AuthLoader';
import ReduxProvider from '../lib/redux/ReduxProvider';
import '../styles/global.css';

export const metadata: Metadata = {
  title: 'Health Mart',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Thêm favicon backup trong head luôn nếu cần */}
        <link rel="icon" href="/images/favicon.ico" />
      </head>
      <body>
        <ReduxProvider>
          <AuthLoader />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
