import type { Metadata } from "next"
import 'antd/dist/reset.css'; // Ant Design reset style
import "../styles/global.css"; // file css của bạn
import "../styles/global.css"

export const metadata: Metadata = {
  title: "Health Mart",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        {/* Thêm favicon backup trong head luôn nếu cần */}
        <link rel="icon" href="/images/favicon.ico" />
      </head> 
      {children}
    </html>
  )
}
